apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: synctargets.brgo.jdvgh.com
spec:
  group: brgo.jdvgh.com
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                repoUrl:
                  type: string
                path:
                  type: string
  scope: Namespaced
  names:
    plural: synctargets
    singular: synctarget
    kind: SyncTarget
    shortNames:
    - st
