# This workflow will build a BrgoCDs servers and run tests against them

name: BrgoCD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.21.3' # The Go version to download (if necessary) and use.
    - name: Init dependencies
      run: |
        #  kubectl
        curl -LO "https://dl.k8s.io/release/v1.28.1/bin/linux/amd64/kubectl"
        curl -LO "https://dl.k8s.io/v1.28.1/bin/linux/amd64/kubectl.sha256"
        echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        sudo chmod +x kubectl
        sudo mkdir -p ~/.local/bin
        sudo cp ./kubectl ~/.local/bin/kubectl
        export PATH=$PATH:~/.local/bin:/root/.local/bin
        # Taskfile
        sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

    - name: Build
      run: task build_go

    - name: Test
      run: task test_go

    - name: Buildah Action
      run: task build_all
